FROM nginx:alpine

# Копируем конфиги и скрипт — указываем путь: nginx/...
COPY nginx/nginx.conf.http /etc/nginx/nginx.conf.http
COPY nginx/nginx.conf.https /etc/nginx/nginx.conf.https
COPY nginx/start-nginx.sh /start-nginx.sh

# Делаем исполняемым
RUN chmod +x /start-nginx.sh

# Запускаем
CMD ["/start-nginx.sh"]